apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stream-upload-file
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod1
    appgw.ingress.kubernetes.io/backend-drain: "true"
spec:
  ingressClassName: azure-application-gateway
  tls:
  - hosts:
      - upstreamfiles.cloudapp008.com
    secretName: upstream-tls
  rules:
  - host: upstreamfiles.cloudapp008.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stream-upload-file
            port:
              number: 8080
